#!/usr/bin/env python3
"""炎龍騎士團2 — 把一張戰場的單位(roster + 出場座標 + EXE 數值)輸出成引擎用 units.json。

組合三方資料:
  FDFIELD 控制段(parse_field):每單位 camp/raw_unit_key/race/cls/lv/group
  FDFIELD 出場段(parse_field positions):(X, Y, raw position key；0=己方部署格)
  EXE 單位表(docs/data/exe_tables/unit.json):各 (race,cls) base hp/mp/ap/dp/dx/mv/ex

輸出 <out>/map<N>_units.json:
  { "map","w","h",
    "own_deploy":[{x,y}...],                       # 己方可部署格(肖像==0)
    "units":[ {camp,cls,cls_name,lv,hp,mp,ap,dp,hit,ev,crit,mv,ex,portrait,x,y} ... ] }

數值:以 (race,cls) 查 EXE base;查不到則用 race 任一 cls 近似,再不到給保底值。
重製 Unit 用此 json;原版資產(著作權)只在本機,不入庫。

hit/ev/crit(worklist 第 8 輪 gap-audit doc42 第 1 項補欄,doc02 §4.1 物理攻擊公式需要):
  - crit:職業暴擊率,查 docs/data/exe_tables/resist_crit.json(EXE 0x5219B 反組譯,已與
    doc02 §7.2 人物成長表交叉驗證吻合,如劍士5%/騎士3%/法師3%),查不到(單位表 cls 超出
    26 種玩家職業,如怪物專屬職業)一律 0(保守預設,非文件明確值)。
  - hit/ev:doc03 明確記載這是「衍生值(由上面計算,直接改無效)」——由 DX + 已裝備武器/
    護甲的 HIT/EV(item.json)在遊戲執行時合成,**不是**「敵/友單位 10B」表的原始欄位
    (該表只有 RA/CL/HP/MP/AP/DP/DX/MV/EX,無 HIT/EV 欄)。remake 尚無裝備系統(doc42 gap
    #12),也沒有敵方武器指定資料可用,故此處用固定近似值(DEFAULT_HIT/DEFAULT_EV,取
    item.json 早期武器/護甲數值的中位數區間),而非反組譯或計算所得——doc42 稱「只是
    匯出腳本未取用」不完全準確,實際是來源表本身缺這兩欄,待裝備系統/HIT-EV 合成公式
    RE 出來後再取代此近似值。

用法:
  python3 export_units.py <extracted/raw> <map_index> <out_dir> [native_unit_tables.json]
"""
import sys, os, json
sys.path.insert(0, os.path.dirname(__file__))
import parse_field

EXE_UNIT = os.path.join(os.path.dirname(__file__), "..", "docs", "data", "exe_tables", "unit.json")
EXE_RESIST_CRIT = os.path.join(os.path.dirname(__file__), "..", "docs", "data", "exe_tables", "resist_crit.json")

# HIT/EV 固定近似值(見檔頭註解:來源表本身無此欄,待裝備系統/合成公式 RE 出來後取代)。
# 落點取 item.json 早期刀劍/防具 HIT(90~100 區間)、EV(5~10 區間)的中位數。
DEFAULT_HIT = 90
DEFAULT_EV = 5

# FDFIELD death_effect type=2 會以 16-bit value 索引 EXE 特殊死亡 handler 表。
# 0x34F74(id39) 把三位元組 00 D3 00 交給 reward dispatcher；
# 0x34FF0(id41) 同理傳 00 D5 00。保留 raw effect，另把可執行 reward 資料化。
SPECIAL_DEATH_REWARDS = {
    39: {"type": 0, "value": 0xD3},
    41: {"type": 0, "value": 0xD5},
}


def native_constructor_for_raw_unit_key(tables, raw_unit_key):
    """Return raw constructor table provenance for one proven FDFIELD b1.

    The optional table JSON is generated by extract_native_unit_tables.py.  A
    raw key outside an evidenced table remains absent rather than indexing
    adjacent EXE data.  No record byte receives a gameplay name here.
    """
    if not tables:
        return None
    if raw_unit_key >= 0x44:
        branch, index = "high_class", raw_unit_key - 0x44
    else:
        branch, index = "lower_class", raw_unit_key
    table = tables.get("tables", {}).get(branch)
    aux_table = tables.get("tables", {}).get("lower_aux") if branch == "lower_class" else None
    if not table or index < 0 or index >= table.get("count", 0):
        return None
    rec = table["records"][index]
    try:
        record = list(bytes.fromhex(rec["bytes_hex"]))
    except (TypeError, ValueError):
        return None
    if len(record) != table.get("record_size"):
        return None
    out = {"branch": branch, "index": index, "record": record}
    if aux_table and index < aux_table.get("count", 0):
        try:
            aux_record = list(bytes.fromhex(aux_table["records"][index]["bytes_hex"]))
        except (TypeError, ValueError):
            return None
        if len(aux_record) != aux_table.get("record_size"):
            return None
        out["aux_record"] = aux_record
    return out


def native_record_word42_for_raw_unit_key(tables, raw_unit_key, level):
    """Compute the constructor input copied to runtime record ``+0x42``.

    This is deliberately a raw ABI projection, not a replacement for the
    editable ``hp`` field.  The constructor at 0x10fe9 receives the value
    from its caller: high selectors use table byte ``+2`` times level; lower
    selectors use lower-class word ``+3`` plus lower-aux byte ``+6`` times
    ``level - 1``.  Missing/malformed provenance remains absent.
    """
    if not tables or level <= 0:
        return None
    native = native_constructor_for_raw_unit_key(tables, raw_unit_key)
    if native is None:
        return None
    record = native["record"]
    if native["branch"] == "high_class":
        if len(record) < 4:
            return None
        return (record[2] | (record[3] << 8)) * level
    aux = native.get("aux_record")
    if aux is None or len(record) < 5 or len(aux) <= 6:
        return None
    base = record[3] | (record[4] << 8)
    return base + aux[6] * (level - 1)


def native_record_word46_for_raw_unit_key(tables, raw_unit_key, level):
    """Compute the constructor input copied to runtime ``+0x44/+0x46``.

    High selectors use table byte ``+4`` times level. Lower selectors use
    lower-class word ``+5`` plus lower-aux byte ``+8`` times ``level - 1``.
    """
    if not tables or level <= 0:
        return None
    native = native_constructor_for_raw_unit_key(tables, raw_unit_key)
    if native is None:
        return None
    record = native["record"]
    if native["branch"] == "high_class":
        if len(record) <= 4:
            return None
        return record[4] * level
    aux = native.get("aux_record")
    if aux is None or len(record) < 7 or len(aux) <= 8:
        return None
    base = record[5] | (record[6] << 8)
    return base + aux[8] * (level - 1)


def crit_by_cls(resist_crit, cls):
    for e in resist_crit:
        if e.get("cls") == cls:
            return e.get("crit_pct", 0)
    return 0  # 查不到(如怪物專屬職業,超出 26 種玩家職業表)保守回 0

# Native unit+2 (map FDICON cache slot) and unit+7 (battle FIGANI/DATO
# consumers) remain distinct runtime fields, but the scripted constructor
# supplies both from the same FDFIELD b1 source: 0x10d7f..0x10efc passes b1 to
# 0x11019, whose returned cache slot becomes unit+2, and directly copies b1 to
# unit+7. FDFIELD b0 is the independent runtime +6 byte. Export b1 as the raw
# map_selector_key; legacy fig remains only a compatibility approximation.

# 職業名(cls_name)顯示錯位 bug 根因(worklist 第 8 輪職業名映射修復):
#   exe unit.json 的 cls_name 是 CLASS_NAMES[cls]——「機械職業(戰鬥動畫/成長曲線用)」,
#   如劍士/戰士/騎士,經確認對照 modify2.md §7 職業魔抗/暴擊表 26 筆全部吻合,這個表本身沒錯。
#   但 modify2.md §8「敵/友單位」表證實同一 (race,cls) 會被多個不同「敘事身分」共用
#   (如 race1,cls2 同時是 士兵/傭兵/精英戰士/鎧甲武士/黑暗戰士/狂戰士 六種不同 NPC),
#   而 map0 實測第一章海盜/士兵的 (race,cls) 甚至是 (1,1)——單位表裡唯一對到的是「黑暗殺手」
#   (idx31,與海盜/士兵毫無關係),base_stats() 取第一筆造成顯示「劍士」這種不相干的機械職業名。
#   ∴ CLASS_NAMES[cls] 只適合當「查不到時的機械職業名 fallback」,不能當敘事身分名。
#   68/96/97 三個 raw unit key 已有各自場景旁證，可作這三筆敘事顯示覆寫；
#   但不能把全部 FDFIELD b1 統稱為 DATO portrait/identity。查不到時
#   (其餘怪物尚未逐一閉合 raw key 對照)
#   留待後續章節逐步補)才落回 CLASS_NAMES[cls] 舊行為,不影響其他已正常顯示的單位。
# 顯示名稱旁證見 docs/data/portrait_names.json +
# docs/knowledge-base/49-character-id-name-table.md(對話反推法,獨立交叉驗證了 68/96/97,
# 另新增 126=ASR-06;同文件說明為何其餘多數怪物 id 目前無法只靠對話反推解出)。
PORTRAIT_CLS_NAME = {
    68: "士兵",     # doc31 §8:友軍海防隊員(第一章 T6 增援,portrait 68)
    96: "盜賊",     # doc31 §8:第一章開場敵方(俗稱「海盜」,青衫攻略敵方列表寫「LV2盜賊」)
    97: "盜賊頭目",  # doc31 §8:第一章 T5 增援首領(青衫攻略「LV3海盜頭目」)
}


def base_stats(exe, race, cls):
    for u in exe:
        if u.get("race") == race and u.get("cls") == cls:
            return u
    for u in exe:                       # 退而求其次:同 race
        if u.get("race") == race:
            return u
    return {"hp": 20, "mp": 0, "ap": 5, "dp": 2, "dx": 1, "mv": 4, "cls_name": f"r{race}c{cls}"}


def main(argv):
    if len(argv) < 4:
        print(__doc__); return 1
    raw, m, out = argv[1], int(argv[2]), argv[3]
    os.makedirs(out, exist_ok=True)
    info = parse_field.parse_map(raw, m)
    exe = json.load(open(EXE_UNIT, encoding="utf-8"))
    resist_crit = json.load(open(EXE_RESIST_CRIT, encoding="utf-8"))
    native_tables = None
    if len(argv) >= 5:
        native_tables = json.load(open(argv[4], encoding="utf-8"))

    # positions[i] 與 control row index 對齊；第三個 word 的完整語意仍保留
    # 為 raw position key。值 0 是己方部署格的已驗證篩選條件。
    positions = info.get("positions", [])           # [X,Y,raw position key]
    own_cells = [{"x": x, "y": y} for (x, y, p) in positions if p == 0]

    units = []
    for i, u in enumerate(info["units"]):
        raw_unit_key = u["raw_unit_key"]
        bs = base_stats(exe, u["race"], u["cls"])
        cls_name = PORTRAIT_CLS_NAME.get(raw_unit_key, bs.get("cls_name", ""))
        rec = {
            "camp": u["camp"], "cls": u["cls"], "cls_name": cls_name,
            # `portrait` remains a legacy editable-schema field. Its source is
            # the raw b1 key, not a universal DATO identity proof.
            "lv": u["lv"], "portrait": raw_unit_key, "group": u.get("group", 0),
            "hp": bs["hp"], "mp": bs["mp"], "ap": bs["ap"], "dp": bs["dp"], "mv": bs["mv"],
            "hit": DEFAULT_HIT, "ev": DEFAULT_EV, "crit": crit_by_cls(resist_crit, u["cls"]),
            "fig": raw_unit_key,  # legacy compatibility approximation; not native unit+2
            "map_selector_key": u["native_map_selector_key"],  # FDFIELD b1 -> 0x11019 -> unit+2 slot
            "native_record_byte6": u["native_record_byte6"],  # FDFIELD b0 -> runtime record +6
            "battle_fig": raw_unit_key,  # FDFIELD b1 -> native unit+7 raw selector
            "native_record_byte8": raw_unit_key,  # FDFIELD b1 -> runtime +8; not universal identity
            "native_record_byte3d": u["native_record_byte3d"],  # FDFIELD b2 -> runtime +0x3d
            "native_source_byte3": u["native_source_byte3"],
            "native_source_byte20": u["native_source_byte20"],
            "native_source_byte25": u["native_source_byte25"],
            "native_record_death_effect": u["native_record_death_effect"],
            # ex:每級經驗(doc02 §4.5「守方每級經驗」;worklist 第 9 輪經驗值系統補接線)。
            # 與 hp/mp/ap/dp/mv 用同一顆 base_stats() (race,cls) 查表——同一份已驗證 EXE
            # 資料(docs/data/exe_tables/unit.json),同一種「該表多筆同 (race,cls) 只取第一筆」
            # 近似(既有限制,見 base_stats() docstring),非另外新造的猜測值。
            "ex": bs.get("ex", 0),
        }
        native = native_constructor_for_raw_unit_key(native_tables, raw_unit_key)
        if native is not None:
            rec["native_constructor"] = native
            word42 = native_record_word42_for_raw_unit_key(native_tables, raw_unit_key, u["lv"])
            if word42 is not None:
                rec["native_record_word42"] = word42
            word46 = native_record_word46_for_raw_unit_key(native_tables, raw_unit_key, u["lv"])
            if word46 is not None:
                rec["native_record_word46"] = word46
        if u.get("inventory"):
            rec["inventory"] = u["inventory"]
        if u.get("inventory_slots"):
            rec["inventory_slots"] = u["inventory_slots"]
        # Raw FDFIELD b13..b16.  This is the initial four-byte portion of the
        # runtime five-byte native command mask; it is intentionally not
        # normalized into the remake's legacy `spells` list.
        if "initial_command_mask" in u:
            rec["initial_command_mask"] = u["initial_command_mask"]
        # FDFIELD b17..b19 are copied verbatim by 0x10fb6..0x10fc5 to
        # runtime +0x34..+0x36. Keep full bytes: +0x34 high bits have other
        # consumers and must not be discarded as if the whole byte were mode.
        for field in ("native_record_byte34", "native_record_byte35", "native_record_byte36"):
            rec[field] = u[field]
        if u.get("death_effect") is not None:
            rec["death_effect"] = u["death_effect"]
            effect = u["death_effect"]
            if effect["type"] in (0, 1):
                rec["death_reward"] = effect
            elif effect["type"] == 2 and effect["value"] in SPECIAL_DEATH_REWARDS:
                rec["death_reward"] = SPECIAL_DEATH_REWARDS[effect["value"]]
        rec["native_source_byte25"] = u["native_source_byte25"]
        if i < len(positions):                       # 固定出場座標(我方會被引擎改放部署格)
            rec["x"], rec["y"] = positions[i][0], positions[i][1]
            rec["native_position_record"] = {
                "x_word": positions[i][0],
                "y_word": positions[i][1],
                "raw_key": positions[i][2],
            }
        units.append(rec)

    res = {"map": m, "w": info["w"], "h": info["h"],
           "own_deploy": own_cells, "chests": info.get("chests", []), "units": units}
    p = os.path.join(out, f"map{m}_units.json")
    json.dump(res, open(p, "w", encoding="utf-8"), ensure_ascii=False, separators=(",", ":"))
    print(f"map{m}: {len(units)} units ({sum(1 for u in units if u['camp']!='own')} 敵/友 配座標), "
          f"{len(own_cells)} 己方部署格 -> {p}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
